### ISSUE TITLE
怎么看function的opcode？

### ISSUE THREAD

**Issue by jianfengye** [ericzhang-cn/opdumper#1]
如题， 比如

<?php
function fibonacci($n) {
    if ($n < 2) {
        return $n;
    }
    return fibonacci($n - 1) + fibonacci($n - 2);
}
var_dump(fibonacci(30));
的opcode为：

line: 2
opcode: ZEND_NOP
op1_type: UNUSED
op2_type: UNUSED
result_type: UNUSED
op1: UNUSED
op2: UNUSED
# result: UNUSED

line: 8
opcode: ZEND_SEND_VAL
op1_type: CONST
op2_type: UNUSED
result_type: UNUSED
op1: 30
op2: UNUSED
# result: UNUSED

line: 8
opcode: ZEND_DO_FCALL
op1_type: CONST
op2_type: UNUSED
result_type: VAR
op1: fibonacci
op2: UNUSED
# result: $0

line: 8
opcode: ZEND_SEND_VAR_NO_REF
op1_type: VAR
op2_type: UNUSED
result_type: UNUSED
op1: $0
op2: UNUSED
# result: UNUSED

line: 8
opcode: ZEND_DO_FCALL
op1_type: CONST
op2_type: UNUSED
result_type: VAR
op1: var_dump
op2: UNUSED
# result: $40

line: 9
opcode: ZEND_RETURN
op1_type: CONST
op2_type: UNUSED
result_type: UNUSED
op1: 1
op2: UNUSED
result: UNUSED

但是只看到ZEND_DO_FCALL，没看到具体的fibonacci内部的opcode，问下这个是可以看的吗？

**Comment by ericzhang-cn** [comment]
目前还没能做到dump function中的代码，这点比较挫。

**Comment by ericzhang-cn** [comment]
一个方法是将function内部代码单独dump
